# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1420, 600)
        MainWindow.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar_gr = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.sidebar_gr.setMinimumSize(QtCore.QSize(200, 0))
        self.sidebar_gr.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sidebar_gr.setStyleSheet("border: none;\n"
"background-color: rgb(255, 85, 127);")
        self.sidebar_gr.setTitle("")
        self.sidebar_gr.setObjectName("sidebar_gr")
        self.horizontalLayout.addWidget(self.sidebar_gr)
        self.main_gr = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.main_gr.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.main_gr.setTitle("")
        self.main_gr.setObjectName("main_gr")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_gr)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_gr = QtWidgets.QGroupBox(parent=self.main_gr)
        self.header_gr.setMinimumSize(QtCore.QSize(0, 77))
        self.header_gr.setMaximumSize(QtCore.QSize(16777215, 77))
        self.header_gr.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.header_gr.setTitle("")
        self.header_gr.setObjectName("header_gr")
        self.verticalLayout.addWidget(self.header_gr)
        self.groupBox = QtWidgets.QGroupBox(parent=self.main_gr)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox.setStyleSheet("")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout.addWidget(self.groupBox)
        self.stas_time = QtWidgets.QGroupBox(parent=self.main_gr)
        self.stas_time.setMinimumSize(QtCore.QSize(0, 75))
        self.stas_time.setMaximumSize(QtCore.QSize(16777215, 75))
        self.stas_time.setStyleSheet("background-color: rgb(36, 38, 28);")
        self.stas_time.setTitle("")
        self.stas_time.setObjectName("stas_time")
        self.verticalLayout.addWidget(self.stas_time)
        self.content = QtWidgets.QGroupBox(parent=self.main_gr)
        self.content.setTitle("")
        self.content.setObjectName("content")
        self.gridLayout = QtWidgets.QGridLayout(self.content)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout.addWidget(self.content)
        self.horizontalLayout.addWidget(self.main_gr)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
