# Form implementation generated from reading ui file 'checkingUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_checkingUI(object):
    def setupUi(self, checkingUI):
        checkingUI.setObjectName("checkingUI")
        checkingUI.resize(1552, 607)
        checkingUI.setStyleSheet("background-color: #0B121F;\n"
"border: none;\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=checkingUI)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(1, 0, 1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar = QtWidgets.QGroupBox(parent=self.groupBox)
        self.sidebar.setMinimumSize(QtCore.QSize(280, 0))
        self.sidebar.setMaximumSize(QtCore.QSize(280, 16777215))
        self.sidebar.setStyleSheet("background-color: #122131;")
        self.sidebar.setTitle("")
        self.sidebar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout.setContentsMargins(35, 0, 35, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.sidebar)
        self.label_2.setMinimumSize(QtCore.QSize(200, 180))
        self.label_2.setMaximumSize(QtCore.QSize(200, 180))
        self.label_2.setStyleSheet("padding-left: 30px;\n"
"background-image: url(D:/NMCNPM/checking_attendance_system/fe/Image_and_icon/logo.png); \n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.sidebar)
        self.groupBox_3.setMinimumSize(QtCore.QSize(200, 58))
        self.groupBox_3.setMaximumSize(QtCore.QSize(200, 58))
        self.groupBox_3.setStyleSheet("background-color: #68D477;\n"
"border-radius: 5px;")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.groupBox_3)
        self.pushButton.setMinimumSize(QtCore.QSize(180, 32))
        self.pushButton.setMaximumSize(QtCore.QSize(180, 32))
        self.pushButton.setStyleSheet("padding-left: 30px;\n"
"background-image: url(D:/NMCNPM/checking_attendance_system/fe/Image_and_icon/icons8-user-30.png); \n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"color: white;\n"
"font: 12pt \"Times New Roman\";")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.sidebar)
        self.groupBox_5.setMinimumSize(QtCore.QSize(200, 58))
        self.groupBox_5.setMaximumSize(QtCore.QSize(200, 58))
        self.groupBox_5.setStyleSheet("background-color: #122131;\n"
"border-radius: 5px;")
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.pushButton_2.setMinimumSize(QtCore.QSize(180, 32))
        self.pushButton_2.setMaximumSize(QtCore.QSize(180, 32))
        self.pushButton_2.setStyleSheet("padding-left: 30px;\n"
"background-image: url(D:/NMCNPM/checking_attendance_system/fe/Image_and_icon/icons8-user-30.png); \n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"color: white;\n"
"font: 12pt \"Times New Roman\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_5)
        spacerItem = QtWidgets.QSpacerItem(20, 210, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.groupBox_6 = QtWidgets.QGroupBox(parent=self.sidebar)
        self.groupBox_6.setMinimumSize(QtCore.QSize(200, 58))
        self.groupBox_6.setMaximumSize(QtCore.QSize(200, 58))
        self.groupBox_6.setStyleSheet("background-color: #122131;\n"
"border-radius: 5px;")
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.logout_button = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.logout_button.setMinimumSize(QtCore.QSize(180, 32))
        self.logout_button.setMaximumSize(QtCore.QSize(180, 32))
        self.logout_button.setStyleSheet("padding-left: 30px;\n"
"background-image: url(D:/NMCNPM/checking_attendance_system/fe/Image_and_icon/icons8-user-30.png); \n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"color: white;\n"
"font: 12pt \"Times New Roman\";")
        self.logout_button.setObjectName("logout_button")
        self.gridLayout_4.addWidget(self.logout_button, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.horizontalLayout.addWidget(self.sidebar)
        self.main = QtWidgets.QGroupBox(parent=self.groupBox)
        self.main.setStyleSheet("")
        self.main.setTitle("")
        self.main.setObjectName("main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header = QtWidgets.QGroupBox(parent=self.main)
        self.header.setMinimumSize(QtCore.QSize(0, 77))
        self.header.setMaximumSize(QtCore.QSize(16777215, 77))
        self.header.setStyleSheet("background-color: #192E44;")
        self.header.setTitle("")
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(parent=self.header)
        self.label.setMinimumSize(QtCore.QSize(120, 37))
        self.label.setMaximumSize(QtCore.QSize(120, 37))
        self.label.setStyleSheet("color: white;\n"
"font: 18pt \"Times New Roman\";")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(308, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.splitter = QtWidgets.QSplitter(parent=self.header)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setHandleWidth(0)
        self.splitter.setObjectName("splitter")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.splitter)
        self.pushButton_4.setMinimumSize(QtCore.QSize(30, 37))
        self.pushButton_4.setMaximumSize(QtCore.QSize(30, 37))
        self.pushButton_4.setStyleSheet("background-color: #9FEF00;\n"
"padding-left: 30px;\n"
"background-image: url(D:/NMCNPM/checking_attendance_system/fe/Image_and_icon/icons8-user-30.png); \n"
"background-repeat: no-repeat;\n"
"background-position: left center;;\n"
"border-top-left-radius: 5px;\n"
"border-bottom-left-radius: 5px;")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.splitter)
        self.pushButton_5.setMinimumSize(QtCore.QSize(240, 37))
        self.pushButton_5.setMaximumSize(QtCore.QSize(240, 37))
        self.pushButton_5.setStyleSheet("border: 1px solid #9FEF00;\n"
"border-top-right-radius: 5px;\n"
"border-bottom-right-radius: 5px;\n"
"color: white;\n"
"font: 12pt \"Times New Roman\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.splitter)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.splitter_2 = QtWidgets.QSplitter(parent=self.header)
        self.splitter_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_2.setHandleWidth(0)
        self.splitter_2.setObjectName("splitter_2")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.splitter_2)
        self.pushButton_6.setMinimumSize(QtCore.QSize(30, 37))
        self.pushButton_6.setMaximumSize(QtCore.QSize(30, 37))
        self.pushButton_6.setStyleSheet("background-color: #9FEF00;\n"
"padding-left: 30px;\n"
"background-image: url(D:/NMCNPM/checking_attendance_system/fe/Image_and_icon/icons8-user-30.png); \n"
"background-repeat: no-repeat;\n"
"background-position: left center;;\n"
"border-top-left-radius: 5px;\n"
"border-bottom-left-radius: 5px;")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.splitter_2)
        self.pushButton_7.setMinimumSize(QtCore.QSize(160, 37))
        self.pushButton_7.setMaximumSize(QtCore.QSize(160, 37))
        self.pushButton_7.setStyleSheet("border: 1px solid #9FEF00;\n"
"border-top-right-radius: 5px;\n"
"border-bottom-right-radius: 5px;\n"
"color: white;\n"
"font: 12pt \"Times New Roman\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_2.addWidget(self.splitter_2)
        spacerItem4 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.splitter_3 = QtWidgets.QSplitter(parent=self.header)
        self.splitter_3.setMinimumSize(QtCore.QSize(0, 37))
        self.splitter_3.setMaximumSize(QtCore.QSize(140, 16777215))
        self.splitter_3.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_3.setHandleWidth(20)
        self.splitter_3.setObjectName("splitter_3")
        self.label_3 = QtWidgets.QLabel(parent=self.splitter_3)
        self.label_3.setMinimumSize(QtCore.QSize(30, 0))
        self.label_3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_3.setStyleSheet("padding-left: 30px;\n"
"background-image: url(D:/NMCNPM/checking_attendance_system/fe/Image_and_icon/icons8-plus-30.png); \n"
"background-repeat: no-repeat;\n"
"background-position: left center;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.splitter_3)
        self.label_4.setMinimumSize(QtCore.QSize(30, 0))
        self.label_4.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_4.setStyleSheet("padding-left: 30px;\n"
"background-image: url(D:/NMCNPM/checking_attendance_system/fe/Image_and_icon/icons8-search-30.png); \n"
"background-repeat: no-repeat;\n"
"background-position: left center;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.splitter_3)
        self.label_5.setMinimumSize(QtCore.QSize(40, 0))
        self.label_5.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_5.setStyleSheet("padding-left: 30px;\n"
"background-image: url(D:/NMCNPM/checking_attendance_system/fe/Image_and_icon/icons8-bell-40.png); \n"
"background-repeat: no-repeat;\n"
"background-position: left center;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.splitter_3)
        spacerItem5 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.header)
        self.pushButton_8.setMinimumSize(QtCore.QSize(35, 37))
        self.pushButton_8.setMaximumSize(QtCore.QSize(35, 37))
        self.pushButton_8.setStyleSheet("background-color: #9FEF00;\n"
"padding-left: 30px;\n"
"background-image: url(D:/NMCNPM/checking_attendance_system/fe/Image_and_icon/icons8-user-30.png); \n"
"background-repeat: no-repeat;\n"
"background-position: left center;;\n"
"border-radius: 15px;\n"
"border: 2px solid #a7a7a7;")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        self.verticalLayout_2.addWidget(self.header)
        spacerItem6 = QtWidgets.QSpacerItem(20, 527, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.horizontalLayout.addWidget(self.main)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        checkingUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(checkingUI)
        QtCore.QMetaObject.connectSlotsByName(checkingUI)

    def retranslateUi(self, checkingUI):
        _translate = QtCore.QCoreApplication.translate
        checkingUI.setWindowTitle(_translate("checkingUI", "MainWindow"))
        self.pushButton.setText(_translate("checkingUI", "Điểm danh"))
        self.pushButton_2.setText(_translate("checkingUI", "Nhân viên"))
        self.logout_button.setText(_translate("checkingUI", "Đăng xuất"))
        self.label.setText(_translate("checkingUI", "Điểm danh"))
        self.pushButton_5.setText(_translate("checkingUI", "HKPTT Company"))
        self.pushButton_7.setText(_translate("checkingUI", "2025-2026"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    checkingUI = QtWidgets.QMainWindow()
    ui = Ui_checkingUI()
    ui.setupUi(checkingUI)
    checkingUI.show()
    sys.exit(app.exec())
