# Form implementation generated from reading ui file 'checkingUI.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_checkingUI(object):
    def setupUi(self, checkingUI):
        checkingUI.setObjectName("checkingUI")
        checkingUI.resize(1520, 697)
        checkingUI.setStyleSheet("background-color: #0B121F;\n"
"border: none;\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=checkingUI)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(1, 0, 1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar = QtWidgets.QGroupBox(parent=self.groupBox)
        self.sidebar.setMinimumSize(QtCore.QSize(280, 0))
        self.sidebar.setMaximumSize(QtCore.QSize(280, 16777215))
        self.sidebar.setStyleSheet("background-color: #122131;")
        self.sidebar.setTitle("")
        self.sidebar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout.setContentsMargins(35, 0, 35, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logo = QtWidgets.QLabel(parent=self.sidebar)
        self.logo.setMinimumSize(QtCore.QSize(200, 180))
        self.logo.setMaximumSize(QtCore.QSize(200, 180))
        self.logo.setStyleSheet("padding-left: 30px;\n"
"background-image: url(D:/NMCNPM/checking_attendance_system/fe/Image_and_icon/logo.png); \n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.verticalLayout.addWidget(self.logo)
        self.fil_attendance = QtWidgets.QGroupBox(parent=self.sidebar)
        self.fil_attendance.setMinimumSize(QtCore.QSize(200, 58))
        self.fil_attendance.setMaximumSize(QtCore.QSize(200, 58))
        self.fil_attendance.setStyleSheet("background-color: #68D477;\n"
"border-radius: 5px;")
        self.fil_attendance.setTitle("")
        self.fil_attendance.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.fil_attendance.setObjectName("fil_attendance")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fil_attendance)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_attendance = QtWidgets.QPushButton(parent=self.fil_attendance)
        self.btn_attendance.setMinimumSize(QtCore.QSize(180, 32))
        self.btn_attendance.setMaximumSize(QtCore.QSize(180, 32))
        self.btn_attendance.setStyleSheet("padding-left: 30px;\n"
"background-image: url(D:/NMCNPM/checking_attendance_system/fe/Image_and_icon/icons8-user-30.png); \n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"color: white;\n"
"font: 12pt \"Times New Roman\";")
        self.btn_attendance.setObjectName("btn_attendance")
        self.gridLayout_2.addWidget(self.btn_attendance, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.fil_attendance)
        self.fil_manage = QtWidgets.QGroupBox(parent=self.sidebar)
        self.fil_manage.setMinimumSize(QtCore.QSize(200, 58))
        self.fil_manage.setMaximumSize(QtCore.QSize(200, 58))
        self.fil_manage.setStyleSheet("background-color: #122131;\n"
"border-radius: 5px;")
        self.fil_manage.setTitle("")
        self.fil_manage.setObjectName("fil_manage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.fil_manage)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_manage = QtWidgets.QPushButton(parent=self.fil_manage)
        self.btn_manage.setMinimumSize(QtCore.QSize(180, 32))
        self.btn_manage.setMaximumSize(QtCore.QSize(180, 32))
        self.btn_manage.setStyleSheet("padding-left: 30px;\n"
"background-image: url(D:/NMCNPM/checking_attendance_system/fe/Image_and_icon/icons8-user-30.png); \n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"color: white;\n"
"font: 12pt \"Times New Roman\";")
        self.btn_manage.setObjectName("btn_manage")
        self.gridLayout_3.addWidget(self.btn_manage, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.fil_manage)
        spacerItem = QtWidgets.QSpacerItem(20, 300, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.fil_logout = QtWidgets.QGroupBox(parent=self.sidebar)
        self.fil_logout.setMinimumSize(QtCore.QSize(200, 58))
        self.fil_logout.setMaximumSize(QtCore.QSize(200, 58))
        self.fil_logout.setStyleSheet("background-color: #122131;\n"
"border-radius: 5px;")
        self.fil_logout.setTitle("")
        self.fil_logout.setObjectName("fil_logout")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.fil_logout)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_logout = QtWidgets.QPushButton(parent=self.fil_logout)
        self.btn_logout.setMinimumSize(QtCore.QSize(180, 32))
        self.btn_logout.setMaximumSize(QtCore.QSize(180, 32))
        self.btn_logout.setStyleSheet("padding-left: 30px;\n"
"background-image: url(D:/NMCNPM/checking_attendance_system/fe/Image_and_icon/icons8-user-30.png); \n"
"background-repeat: no-repeat;\n"
"background-position: left center;\n"
"color: white;\n"
"font: 12pt \"Times New Roman\";")
        self.btn_logout.setObjectName("btn_logout")
        self.gridLayout_4.addWidget(self.btn_logout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.fil_logout)
        self.horizontalLayout.addWidget(self.sidebar)
        self.main = QtWidgets.QGroupBox(parent=self.groupBox)
        self.main.setStyleSheet("")
        self.main.setTitle("")
        self.main.setObjectName("main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header = QtWidgets.QGroupBox(parent=self.main)
        self.header.setMinimumSize(QtCore.QSize(0, 77))
        self.header.setMaximumSize(QtCore.QSize(16777215, 77))
        self.header.setStyleSheet("background-color: #192E44;")
        self.header.setTitle("")
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.header_title = QtWidgets.QLabel(parent=self.header)
        self.header_title.setMinimumSize(QtCore.QSize(120, 37))
        self.header_title.setMaximumSize(QtCore.QSize(120, 37))
        self.header_title.setStyleSheet("color: white;\n"
"font: 18pt \"Times New Roman\";")
        self.header_title.setObjectName("header_title")
        self.horizontalLayout_2.addWidget(self.header_title)
        spacerItem2 = QtWidgets.QSpacerItem(276, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.company = QtWidgets.QSplitter(parent=self.header)
        self.company.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.company.setHandleWidth(0)
        self.company.setObjectName("company")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.company)
        self.pushButton_4.setMinimumSize(QtCore.QSize(30, 37))
        self.pushButton_4.setMaximumSize(QtCore.QSize(30, 37))
        self.pushButton_4.setStyleSheet("background-color: #9FEF00;\n"
"padding-left: 30px;\n"
"background-image: url(D:/NMCNPM/checking_attendance_system/fe/Image_and_icon/icons8-user-30.png); \n"
"background-repeat: no-repeat;\n"
"background-position: left center;;\n"
"border-top-left-radius: 5px;\n"
"border-bottom-left-radius: 5px;")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.btn_company_name = QtWidgets.QPushButton(parent=self.company)
        self.btn_company_name.setMinimumSize(QtCore.QSize(240, 37))
        self.btn_company_name.setMaximumSize(QtCore.QSize(240, 37))
        self.btn_company_name.setStyleSheet("border: 1px solid #9FEF00;\n"
"border-top-right-radius: 5px;\n"
"border-bottom-right-radius: 5px;\n"
"color: white;\n"
"font: 12pt \"Times New Roman\";")
        self.btn_company_name.setObjectName("btn_company_name")
        self.horizontalLayout_2.addWidget(self.company)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.time = QtWidgets.QSplitter(parent=self.header)
        self.time.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.time.setHandleWidth(0)
        self.time.setObjectName("time")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.time)
        self.pushButton_6.setMinimumSize(QtCore.QSize(30, 37))
        self.pushButton_6.setMaximumSize(QtCore.QSize(30, 37))
        self.pushButton_6.setStyleSheet("background-color: #9FEF00;\n"
"padding-left: 30px;\n"
"background-image: url(D:/NMCNPM/checking_attendance_system/fe/Image_and_icon/icons8-user-30.png); \n"
"background-repeat: no-repeat;\n"
"background-position: left center;;\n"
"border-top-left-radius: 5px;\n"
"border-bottom-left-radius: 5px;")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.btn_year = QtWidgets.QPushButton(parent=self.time)
        self.btn_year.setMinimumSize(QtCore.QSize(160, 37))
        self.btn_year.setMaximumSize(QtCore.QSize(160, 37))
        self.btn_year.setStyleSheet("border: 1px solid #9FEF00;\n"
"border-top-right-radius: 5px;\n"
"border-bottom-right-radius: 5px;\n"
"color: white;\n"
"font: 12pt \"Times New Roman\";")
        self.btn_year.setObjectName("btn_year")
        self.horizontalLayout_2.addWidget(self.time)
        spacerItem4 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.splitter_3 = QtWidgets.QSplitter(parent=self.header)
        self.splitter_3.setMinimumSize(QtCore.QSize(0, 37))
        self.splitter_3.setMaximumSize(QtCore.QSize(126, 16777215))
        self.splitter_3.setStyleSheet("margin: 2px;\n"
"")
        self.splitter_3.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_3.setHandleWidth(1)
        self.splitter_3.setObjectName("splitter_3")
        self.btn_add = QtWidgets.QLabel(parent=self.splitter_3)
        self.btn_add.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_add.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_add.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_add.setStyleSheet("\n"
"background-image: url(D:/NMCNPM/checking_attendance_system/fe/Image_and_icon/icons8-plus-30.png); \n"
"background-repeat: no-repeat;\n"
"background-position: center center;\n"
"")
        self.btn_add.setText("")
        self.btn_add.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.btn_add.setObjectName("btn_add")
        self.btn_search = QtWidgets.QLabel(parent=self.splitter_3)
        self.btn_search.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_search.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_search.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_search.setStyleSheet("background-image: url(D:/NMCNPM/checking_attendance_system/fe/Image_and_icon/icons8-search-30.png); \n"
"background-repeat: no-repeat;\n"
"background-position: center center;\n"
"")
        self.btn_search.setText("")
        self.btn_search.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.btn_search.setIndent(-1)
        self.btn_search.setOpenExternalLinks(False)
        self.btn_search.setObjectName("btn_search")
        self.btn_bell = QtWidgets.QLabel(parent=self.splitter_3)
        self.btn_bell.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_bell.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_bell.setStyleSheet("padding-left: 30px;\n"
"background-image: url(D:/NMCNPM/checking_attendance_system/fe/Image_and_icon/icons8-bell-40.png); \n"
"background-repeat: no-repeat;\n"
"background-position: center center;\n"
"")
        self.btn_bell.setText("")
        self.btn_bell.setObjectName("btn_bell")
        self.horizontalLayout_2.addWidget(self.splitter_3)
        spacerItem5 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.btn_admin = QtWidgets.QPushButton(parent=self.header)
        self.btn_admin.setMinimumSize(QtCore.QSize(35, 37))
        self.btn_admin.setMaximumSize(QtCore.QSize(35, 37))
        self.btn_admin.setStyleSheet("background-color: #9FEF00;\n"
"padding-left: 30px;\n"
"background-image: url(D:/NMCNPM/checking_attendance_system/fe/Image_and_icon/icons8-user-30.png); \n"
"background-repeat: no-repeat;\n"
"background-position: left center;;\n"
"border-radius: 15px;\n"
"border: 2px solid #a7a7a7;")
        self.btn_admin.setText("")
        self.btn_admin.setObjectName("btn_admin")
        self.horizontalLayout_2.addWidget(self.btn_admin)
        self.verticalLayout_2.addWidget(self.header)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.main)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 70))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 70))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.main)
        self.groupBox_4.setStyleSheet("background-color: #192E44;")
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.horizontalLayout.addWidget(self.main)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        checkingUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(checkingUI)
        QtCore.QMetaObject.connectSlotsByName(checkingUI)

    def retranslateUi(self, checkingUI):
        _translate = QtCore.QCoreApplication.translate
        checkingUI.setWindowTitle(_translate("checkingUI", "MainWindow"))
        self.btn_attendance.setText(_translate("checkingUI", "Điểm danh"))
        self.btn_manage.setText(_translate("checkingUI", "Nhân viên"))
        self.btn_logout.setText(_translate("checkingUI", "Đăng xuất"))
        self.header_title.setText(_translate("checkingUI", "Điểm danh"))
        self.btn_company_name.setText(_translate("checkingUI", "HKPTT Company"))
        self.btn_year.setText(_translate("checkingUI", "2025-2026"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    checkingUI = QtWidgets.QMainWindow()
    ui = Ui_checkingUI()
    ui.setupUi(checkingUI)
    checkingUI.show()
    sys.exit(app.exec())
